@Anticipation.API_HostAddress = http://localhost:5216

POST {{Anticipation.API_HostAddress}}/api/v1/anticipations
Content-Type: application/json

{
	"creator_id": "user-001",
	"valor_solicitado": 1200.50,
	"data_solicitacao": "2026-03-08T10:00:00Z"
}

###

GET {{Anticipation.API_HostAddress}}/api/v1/anticipations/creator/user-001
Accept: application/json

###
